#pragma once

#define ICON_FONT_TRASH_CAN_OUTLINE u8"\ufa79"
#define ICON_FONT_PLUS u8"\uf415"
#define ICON_FONT_MINUS u8"\uf374"
#define ICON_FONT_REFRESH u8"\uf450"
#define ICON_FONT_CHEVRON_LEFT_BOX u8"\uf9d7"
#define ICON_FONT_CHEVRON_RIGHT_BOX u8"\uf9d9"
#define ICON_FONT_CHEVRON_UP_BOX u8"\uf9db"
#define ICON_FONT_CHEVRON_DOWN_BOX u8"\uf9d5"
#define ICON_FONT_ALERT_OCTAGON u8"\uf029"
#define ICON_FONT_ALERT u8"\uf026"
#define ICON_FONT_ALERT_CIRCLE u8"\uf028"

#define BAR_LABEL_INFOS ICON_FONT_ALERT_CIRCLE
#define BAR_LABEL_WARNINGS ICON_FONT_ALERT
#define BAR_LABEL_ERROR ICON_FONT_ALERT_OCTAGON

#define MENU_LABEL_REFRESH ICON_FONT_REFRESH
#define MENU_LABEL_CLEAR ICON_FONT_TRASH_CAN_OUTLINE
#define MENU_LABEL_ARROW_LEFT ICON_FONT_CHEVRON_LEFT_BOX
#define MENU_LABEL_ARROW_RIGHT ICON_FONT_CHEVRON_RIGHT_BOX
#define MENU_LABEL_ARROW_UP ICON_FONT_CHEVRON_UP_BOX
#define MENU_LABEL_ARROW_BOTTOM ICON_FONT_CHEVRON_DOWN_BOX
