set(LUA_JIT_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/luajit)

if(USE_SHARED_LIBS)
	set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
	set(LLVM_USE_CRT_DEBUG MDd CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_MINSIZEREL MD CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_RELEASE MD CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_RELWITHDEBINFO MD CACHE STRING "" FORCE)
else()
	set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
	set(LLVM_USE_CRT_DEBUG MTd CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_MINSIZEREL MT CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_RELEASE MT CACHE STRING "" FORCE)
	set(LLVM_USE_CRT_RELWITHDEBINFO MT CACHE STRING "" FORCE)
endif()

if(NOT CMAKE_DEBUG_POSTFIX)
	set(CMAKE_DEBUG_POSTFIX _debug)
endif()
if(NOT CMAKE_RELEASE_POSTFIX)
	set(CMAKE_RELEASE_POSTFIX)
endif()
if(NOT CMAKE_MINSIZEREL_POSTFIX)
	set(CMAKE_MINSIZEREL_POSTFIX _minsizerel)
endif()
if(NOT CMAKE_RELWITHDEBINFO_POSTFIX)
	set(CMAKE_RELWITHDEBINFO_POSTFIX _reldeb)
endif()

add_subdirectory(${LUA_JIT_INCLUDE_DIR} EXCLUDE_FROM_ALL)
    
set_target_properties(libluajit PROPERTIES LINKER_LANGUAGE C)
set_target_properties(luajit PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(minilua PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(libluajit PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(buildvm PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(buildvm_arch_h PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(lj_gen_folddef PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(lj_gen_headers PROPERTIES FOLDER 3rdparty/luajit)
set_target_properties(lj_gen_vm_s PROPERTIES FOLDER 3rdparty/luajit)	

if(USE_SHARED_LIBS)
	set_target_properties(libluajit PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}/plugins")
	set_target_properties(libluajit PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}/plugins")
	set_target_properties(libluajit PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${FINAL_BIN_DIR}/plugins")
	set_target_properties(libluajit PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${FINAL_BIN_DIR}/plugins")
endif()

set(LUA_JIT_LIBRARIES libluajit)
