FetchContent_Declare(
	httplib
	GIT_REPOSITORY	https://github.com/yhirose/cpp-httplib.git
	GIT_TAG			v0.18.1
	SOURCE_DIR		${CMAKE_CURRENT_SOURCE_DIR}/build/_deps/httplib
	GIT_PROGRESS	true
	GIT_SHALLOW		true
)

FetchContent_GetProperties(httplib) 
if(NOT httplib_POPULATED)
	FetchContent_Populate(httplib)
	
	set(HTTPLIB_REQUIRE_OPENSSL ON CACHE BOOL "" FORCE)

	if(USE_SHARED_LIBS)
		set(HTTPLIB_COMPILE ON CACHE BOOL "" FORCE) ## needed for sahred lib
		set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
		set(LLVM_USE_CRT_DEBUG MDd CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_MINSIZEREL MD CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELEASE MD CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELWITHDEBINFO MD CACHE STRING "" FORCE)
		set(OPENSSL_USE_STATIC_LIBS OFF CACHE BOOL "" FORCE)
		if(MSVC)
			set(OPENSSL_MSVC_STATIC_RT OFF CACHE BOOL "" FORCE)
		endif()
	else()
		add_definitions(-Dhttplib_STATICLIB)
		set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
		set(LLVM_USE_CRT_DEBUG MTd CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_MINSIZEREL MT CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELEASE MT CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELWITHDEBINFO MT CACHE STRING "" FORCE)
		set(OPENSSL_USE_STATIC_LIBS ON CACHE BOOL "" FORCE)
		if(MSVC)
			set(OPENSSL_MSVC_STATIC_RT ON CACHE BOOL "" FORCE)
		endif()
	endif()
	
	set(HTTPLIB_INSTALL OFF CACHE BOOL "" FORCE)

	if(NOT CMAKE_DEBUG_POSTFIX)
	  set(CMAKE_DEBUG_POSTFIX _debug)
	endif()
	if(NOT CMAKE_RELEASE_POSTFIX)
	  set(CMAKE_RELEASE_POSTFIX)
	endif()
	if(NOT CMAKE_MINSIZEREL_POSTFIX)
	  set(CMAKE_MINSIZEREL_POSTFIX _minsizerel)
	endif()
	if(NOT CMAKE_RELWITHDEBINFO_POSTFIX)
	  set(CMAKE_RELWITHDEBINFO_POSTFIX _reldeb)
	endif()
	
	##EXCLUDE_FROM_ALL reject install for this target
	add_subdirectory(${httplib_SOURCE_DIR} EXCLUDE_FROM_ALL)	

	if(USE_SHARED_LIBS)
		set(CPP_HTTPLIB_LIBRARIES httplib)
		set_target_properties(httplib PROPERTIES FOLDER 3rdparty/Shared)
		set_target_properties(httplib PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
		set_target_properties(httplib PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")
		set_target_properties(httplib PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${FINAL_BIN_DIR}")
		set_target_properties(httplib PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${FINAL_BIN_DIR}")
	else()
		set(CPP_HTTPLIB_LIBRARIES httplib::httplib)
	endif()

	set(CPP_HTTPLIB_INCLUDE_DIR ${httplib_SOURCE_DIR})
	include_directories(${CPP_HTTPLIB_INCLUDE_DIR})
endif()
