name: linux

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**

jobs:
  build_Linux_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        token: ${{ secrets.PAT_SUBMODULES }}
        submodules: recursive
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libwayland-dev
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: bin/${{ github.event.repository.name }}*
